apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: vault-backup
  labels: {{ toYaml .Values.labels | nindent 5 }}
  annotations: {{ toYaml .Values.annotations | nindent 5 }}
spec:
  schedule: {{ .Values.schedule | quote }}
  successfulJobsHistoryLimit: {{ .Values.successfulJobsHistoryLimit | default 3 }}
  concurrencyPolicy: {{ .Values.concurrencyPolicy | default "Forbid" }}
  failedJobsHistoryLimit: {{ .Values.failedJobsHistoryLimit | default 3 }}
  startingDeadlineSeconds: {{ .Values.startingDeadlineSeconds | default 900 }} 
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            app: vault-backup
          annotations: {{ toYaml .Values.podAnnotations | nindent 5 }}
        spec:
          {{- if .Values.priorityClassName }}
          priorityClassName: {{ .Values.priorityClassName }}
          {{- end }}
          containers:
          - name: {{ .Chart.Name }}
            image: {{ .Values.image.registry }}/{{ .Values.image.repository }}:{{ default .Chart.AppVersion .Values.image.tag }}
            imagePullPolicy: {{ .Values.image.pullPolicy }}
            {{- if .Values.command }}
            command: {{ .Values.command }}
            {{- end }}
            {{- if .Values.args }}
            args: {{ .Values.args }}
            {{- end }}
            env: 
            - name: VAULT_SECRET_PATH
              value: {{ .Values.vault.secretPath }}
            - name: VAULT_SKIP_VERIFY
              value: "true"
            envFrom:
              - configMapRef:
                  name: vault-backup-config
              - secretRef:
                  name: vault-backup-secret
            {{- if .Values.resources }}
            resources: {{- toYaml .Values.resources | nindent 14 }}
            {{- end }}
            volumeMounts:
            - name: private-key
              mountPath: /opt/private-key.pem
              subPath: private-key.pem
              readOnly: true
          restartPolicy: {{ default "OnFailure" .Values.restartPolicy }}
          volumes:
            - name: private-key
              secret:
                secretName: vault-backup-private-key