apiVersion: v1
kind: Secret
metadata:
  name: vault-backup-secret
  labels:
    app: vault-backup
type: Opaque
data:
  S3_ACCESS_KEY: {{ .Values.s3.accesskey | b64enc }}
  S3_SECRET_KEY: {{ .Values.s3.secretkey | b64enc }}
  VAULT_TOKEN: {{ .Values.vault.token | b64enc }}